struct Song {
    enum Tag: String {
        case fourAD = "4AD"
        case cover = "Cover"
        case decade1940s = "1940s"
        case decade1950s = "1950s"
        case decade1960s = "1960s"
        case decade1970s = "1970s"
        case decade1980s = "1980s"
        case decade1990s = "1990s"
        case decade2000s = "2000s"
        case decade2010s = "2010s"
        case golden2004 = "2004 Golden Year"
        case platinum2016 = "2016 Platinum Year"
        case lizFraser = "Liz Fraser"
        case debut = "Début"
        case sample = "Sample"
        case mashup = "Mashup"
        case hopeSandoval = "Hope Sandoval"
        case jarvisCocker = "Jarvis Cocker"
        case husbandWife = "Husband/Wife"
        case canadian = "Canadian"
        case indie = "Indie"
        case openingTrack = "Opening Track"
        case scottish = "Scottish"
        case electronic = "Electronic"
        case sciFi = "SciFi"
        case oneLittleIndian = "One Little Indian"
        case giorgioMoroder = "Giorgio Moroder"
        case disco = "Disco"
        case brothers = "Brothers"
        case tapeLoops = "Tape Loops"
        case bassSolo = "Bass Solo"
        case rickBeato = "Rick Beato"
        case punk = "Punk"
        case kathleenHanna = "Kathleen Hanna"
        case christmasCarol = "Christmas Carol"
        case spokenWord = "Spoken Word"
        case tripHop = "Trip Hop"
        case bristol = "Bristol"
        case isaacHayes = "Isaac Hayes"
        case timeSignatureChange = "Time Signature Change"
        case ringTone = "Ring Tone"
        case compilationAlbum = "Compilation Album"
        case swedish = "Swedish"
        case dogsInVideo = "Dogs In Video"
        case waltzTime = "Waltz Time"
        case remix = "Remix"
        case house = "House"
        case indieDance = "Indie/Dance"
        case drugs = "Drugs"
        case hype = "Hype"
        case noBass = "No Bass"
        case postPunk = "Post-punk"
        case actor = "Actor"
        case kids = "Kids"
        case reggae = "Reggae"
        case dub = "Dub"
        case slyRobbie = "Sly & Robbie"
        case irish = "Irish"
        case jamaican = "Jamaican"
        case sixMusic = "6music"
        case cornwall = "Cornwall"
        case newRomantic = "New Romantic"
        case riotGrrrl = "Riot Grrrl"
        case addedBeat = "Added Beat"
        case skippedBeat = "Skipped Beat"
        case glam = "Glam"
        case movie = "Movie"
        case twoForOne = "2 for 1"
        case icelandic = "Icelandic"
        case cornish = "Cornish"
        case belgian = "Belgian"
        case french = "French"
        case puns = "Puns"
        case classical = "Classical"
        case folk = "Folk"
        case brass = "Brass"
        case welsh = "Welsh"
        case instrumental = "Instrumental"
        case fWord = "F Word"
        case shouty = "Shouty"
        case rockOpera = "Rock Opera"
        case glitch = "Glitch"
        case ninjaTune = "Ninja Tune"
        case collaboration = "Collaboration"
        case longSongs = "Long Songs"
        case complex = "Complex"
        case ukulele = "Ukulele"
        case reinvention = "Reinvention"
        case ep = "EP"
        case twoDrummers = "Two Drummers"
        case guestVocals = "Guest Vocals"
        case brighton = "Brighton"
        case manchester = "Manchester"
        case northampton = "Northampton"
        case comeback = "Comeback"
        case liverpool = "Liverpool"
        case ska = "Ska"
        case twoTone = "2 Tone"
        case coventry = "Coventry"
        case terryHall = "Terry Hall"
        case live = "Live"
        case posthumous = "Posthumous"
        case samples = "Samples"
        case tr909 = "TR-909"
        case lonelyIsAnEyesore = "Lonely Is An Eyesore"
        case italianHouse = "Italian House"
        case leeds = "Leeds"
        case funk = "Funk"
    }

    enum Country: String {
        case iceland   = "🇮🇸"
        case italy     = "🇮🇹"
        case poland    = "🇵🇱"
        case sweden    = "🇸🇪"
        case jamaica   = "🇯🇲"
        case uk        = "🇬🇧"
        case usa       = "🇺🇸"
        case australia = "🇦🇺"
        case canada    = "🇨🇦"
        case ireland   = "🇮🇪"
        case belgium   = "🇧🇪"
    }

    enum HomePageStyle {
        case fullPanel
        case semiPanel
        case listing
    }

    let id:       Int
    let style:    HomePageStyle
    let dir:      String
    let artist:   String
    let title:    String
    let album:    String
    let released: String
    let maxRez:   Int
    let tags:     [Tag]
    let country:  [Country]
    let video:    SongVideo
    let links:    [SongLink]
}
